spring:
  application:
    name: course-service
  datasource:
    url: jdbc:mysql://localhost:3306/course-service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password: Super
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka